#!/bin/bash

#script to open things from terminal into an arbitrary i3 workspace

##APP=$2

for C in "$@" ; do
	if [[ ! $C =~ [0-9]+ ]] ; then
		APP+=" $C"
		echo $APP
	fi
done 

echo "Opening$APP in workspace $1..." 

/usr/bin/i3-msg "workspace "$1 &>/dev/null && exec $APP
